# Generated by Django 2.0.9 on 2018-12-21 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('YaId', models.CharField(max_length=200, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('limit_1H', models.FloatField(default=0.0)),
                ('limit_24H', models.FloatField(default=0.0)),
                ('minimum', models.FloatField(default=0.0)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('parks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.Park')),
            ],
        ),
    ]
