# Generated by Django 2.1.4 on 2019-02-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='parks',
            new_name='park',
        ),
    ]
