# Generated by Django 2.1.4 on 2019-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiwi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiwi_park',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
